import sys
import easyocr
import numpy as np
from PIL import Image

# Fix Windows encoding issue with EasyOCR progress bars
if sys.platform.startswith('win'):
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except Exception:
        pass

# Initialize the EasyOCR reader
try:
    reader = easyocr.Reader(['en'], gpu=False)
except Exception as e:
    print(f"Warning: Could not initialize EasyOCR reader: {e}")
    reader = None

def check_ocr_watermark(image_file):
    """
    Extracts text from an image using EasyOCR and checks for AI tool watermarks.
    
    Args:
        image_file: file-like object or path
        
    Returns:
        tuple: (bool is_ai, str reason)
    """
    if reader is None:
        return False, "OCR system not initialized."

    ai_keywords = [
        'midjourney', 'ai generated', 'generated by ai', 
        'firefly', 'dall-e', 'stable diffusion', 'openai', 'gemini', 'al generated'
    ]
    
    try:
        # Convert PIL image to numpy array for EasyOCR
        img = Image.open(image_file)
        if img.mode != 'RGB':
            img = img.convert('RGB')
        img_np = np.array(img)
        
        # Read text
        results = reader.readtext(img_np)
        
        # results is a list of tuples: (bbox, text, confidence)
        extracted_texts = [text.lower() for (_, text, _) in results]
        full_text = " ".join(extracted_texts)
        # Remove punctuation to catch words like "AI-Generated"
        full_text = full_text.replace('-', ' ').replace('_', ' ')
        
        for keyword in ai_keywords:
            if keyword in full_text:
                return True, f"AI watermark detected (Keyword: '{keyword}')"
                
        return False, "No AI-related watermarks found in image text."
        
    except Exception as e:
        return False, f"Error processing OCR: {str(e)}"
